# Developer build from a checked-out source tree: makepkg --syncdeps
# Release/AUR recipes with verified source hashes are generated by build_linux.py.
pkgname=pokenux
pkgver=1.1.0
pkgrel=1
pkgdesc='Pokémon terminal companion with quizzes and virtual cards'
arch=('x86_64' 'aarch64')
url='https://github.com/FrancoisBasset/pokenux'
license=('MIT' 'PSF-2.0')
depends=('glibc>=2.28' 'gcc-libs' 'zlib' 'ca-certificates')
makedepends=('python>=3.11' 'uv=0.11.23')
options=('!strip' '!debug')

build() {
  cd "$startdir"
  python scripts/build_linux.py --formats tar --output "$srcdir/release"
  tar -xzf "$srcdir/release/pokenux-$pkgver-linux-$CARCH.tar.gz" -C "$srcdir"
}

check() {
  "$srcdir/pokenux-$pkgver-linux-$CARCH/pokenux" --check
}

package() {
  local bundle="$srcdir/pokenux-$pkgver-linux-$CARCH"
  install -d "$pkgdir/opt" "$pkgdir/usr/bin" "$pkgdir/usr/share/doc/pokenux" \
    "$pkgdir/usr/share/licenses/pokenux"
  cp -a "$bundle" "$pkgdir/opt/pokenux"
  printf '#!/bin/sh\nexec /opt/pokenux/pokenux "$@"\n' > "$pkgdir/usr/bin/pokenux"
  chmod 755 "$pkgdir/usr/bin/pokenux"
  cp -a "$bundle/share/." "$pkgdir/usr/share/"
  install -m644 "$bundle/LICENSE" "$pkgdir/usr/share/licenses/pokenux/LICENSE"
  install -m644 "$bundle/"*.md "$bundle/LICENSE" "$bundle/pyproject.toml" "$bundle/THIRD_PARTY_NOTICES.txt" \
    "$pkgdir/usr/share/doc/pokenux/"
  cp -a "$bundle/docs" "$bundle/.github" "$pkgdir/usr/share/doc/pokenux/"
}
